//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.13 at 02:54:56 PM CEST 
//


package it.unibo.cs.swarch.protocol.simplexml.classes;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Order;
import org.simpleframework.xml.Root;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="moveOf">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="6"/>
 *               &lt;maxLength value="15"/>
 *               &lt;pattern value="\w+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="card">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="AH"/>
 *               &lt;enumeration value="2H"/>
 *               &lt;enumeration value="3H"/>
 *               &lt;enumeration value="4H"/>
 *               &lt;enumeration value="5H"/>
 *               &lt;enumeration value="6H"/>
 *               &lt;enumeration value="7H"/>
 *               &lt;enumeration value="8H"/>
 *               &lt;enumeration value="9H"/>
 *               &lt;enumeration value="10H"/>
 *               &lt;enumeration value="JH"/>
 *               &lt;enumeration value="QH"/>
 *               &lt;enumeration value="KH"/>
 *               &lt;enumeration value="AC"/>
 *               &lt;enumeration value="2C"/>
 *               &lt;enumeration value="3C"/>
 *               &lt;enumeration value="4C"/>
 *               &lt;enumeration value="5C"/>
 *               &lt;enumeration value="6C"/>
 *               &lt;enumeration value="7C"/>
 *               &lt;enumeration value="8C"/>
 *               &lt;enumeration value="9C"/>
 *               &lt;enumeration value="10C"/>
 *               &lt;enumeration value="JC"/>
 *               &lt;enumeration value="QC"/>
 *               &lt;enumeration value="KC"/>
 *               &lt;enumeration value="AD"/>
 *               &lt;enumeration value="2D"/>
 *               &lt;enumeration value="3D"/>
 *               &lt;enumeration value="4D"/>
 *               &lt;enumeration value="5D"/>
 *               &lt;enumeration value="6D"/>
 *               &lt;enumeration value="7D"/>
 *               &lt;enumeration value="8D"/>
 *               &lt;enumeration value="9D"/>
 *               &lt;enumeration value="10D"/>
 *               &lt;enumeration value="JD"/>
 *               &lt;enumeration value="QD"/>
 *               &lt;enumeration value="KD"/>
 *               &lt;enumeration value="AS"/>
 *               &lt;enumeration value="2S"/>
 *               &lt;enumeration value="3S"/>
 *               &lt;enumeration value="4S"/>
 *               &lt;enumeration value="5S"/>
 *               &lt;enumeration value="6S"/>
 *               &lt;enumeration value="7S"/>
 *               &lt;enumeration value="8S"/>
 *               &lt;enumeration value="9S"/>
 *               &lt;enumeration value="10S"/>
 *               &lt;enumeration value="JS"/>
 *               &lt;enumeration value="QS"/>
 *               &lt;enumeration value="KS"/>
 *               &lt;enumeration value="NOT A VALID CARD"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nextTurnOf" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="6"/>
 *               &lt;maxLength value="15"/>
 *               &lt;pattern value="\w+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Default(DefaultType.FIELD)
@Order (elements = {
    "moveOf",
    "card",
    "nextTurnOf"
})
@Root(name = "moveReply")
public class MoveReply {

    @Element(required = true)
    protected String moveOf;
    @Element(required = true)
    protected String card;
    protected String nextTurnOf;

    /**
     * Gets the value of the moveOf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveOf() {
        return moveOf;
    }

    /**
     * Sets the value of the moveOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveOf(String value) {
        this.moveOf = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCard(String value) {
        this.card = value;
    }

    /**
     * Gets the value of the nextTurnOf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextTurnOf() {
        return nextTurnOf;
    }

    /**
     * Sets the value of the nextTurnOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextTurnOf(String value) {
        this.nextTurnOf = value;
    }

}
