//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.13 at 02:54:56 PM CEST 
//


package it.unibo.cs.swarch.protocol.simplexml.classes;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Order;
import org.simpleframework.xml.Root;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userThatHasLeft">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="6"/>
 *               &lt;maxLength value="15"/>
 *               &lt;pattern value="\w+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="botName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="4"/>
 *               &lt;maxLength value="15"/>
 *               &lt;pattern value="\w+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Default(DefaultType.FIELD)
@Order (elements = {
    "userThatHasLeft",
    "botName"
})
@Root(name = "userHasLeftTheTable")
public class UserHasLeftTheTable {

    @Element(required = true)
    protected String userThatHasLeft;
    @Element(required = true)
    protected String botName;

    /**
     * Gets the value of the userThatHasLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserThatHasLeft() {
        return userThatHasLeft;
    }

    /**
     * Sets the value of the userThatHasLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserThatHasLeft(String value) {
        this.userThatHasLeft = value;
    }

    /**
     * Gets the value of the botName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBotName() {
        return botName;
    }

    /**
     * Sets the value of the botName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBotName(String value) {
        this.botName = value;
    }

}
